<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12">
			    	<h1>Day 234</h1>
			    	<ol class="breadcrumb">
					  <li><a href="/">Home</a></li>
					  <li><a href="/articles">Articles</a></li>
					  <li class="active">Day</li>
					</ol>
				</div>
			</div>
	    </div> <!-- /container -->
<div class="container">
<div class="container">
	    	<div class="lessons-wrap">
	    		<div class="class-thumbs-wrap">
			    	<div class="row">
			    		<div class="col-xs-12 col-sm-12">
			    			<div class="coursthumbs">
			    				<ul class="nopadding nomargin listnone listing-view">
			    					<li class="less-listing course-thumbs cats">
			    						<a href=""></a>
			    						<div class="bg-arrow">
					    						<div class="row">
					    							<div class="col-xs-5 col-sm-5">
					    								<div class="cat-image">
					    									<a href=""><img src="/images/content/samplecat.jpg" alt="category"/></a>
					    								</div>
					    							</div>
						    						<div class="col-xs-7 col-sm-7">
							    						<div class="less-title">
							    							<a href="">Beginning Literacy</a>
							    						</div>
							    						<p>Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Nullam quis risus eget urna mollis ornare vel eu leo.</p>
						    						</div>
					    						</div>
			    						</div>
			    					</li>
			    					<li class="less-listing course-thumbs cats">
			    						<a href=""></a>
			    						<div class="bg-arrow">
					    						<div class="row">
					    							<div class="col-xs-5 col-sm-5">
					    								<div class="cat-image">
					    									<a href=""><img src="/images/content/samplecat.jpg" alt="category"/></a>
					    								</div>
					    							</div>
						    						<div class="col-xs-7 col-sm-7">
							    						<div class="less-title">
							    							<a href="">Beginning Literacy</a>
							    						</div>
							    						<p>Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Nullam quis risus eget urna mollis ornare vel eu leo.</p>
						    						</div>
					    						</div>
					    						
			    						</div>
			    					</li>
			    					<li class="less-listing course-thumbs cats">
			    						<a href=""></a>
			    						<div class="bg-arrow">
					    						<div class="row">
					    							<div class="col-xs-5 col-sm-5">
					    								<div class="cat-image">
					    									<a href=""><img src="/images/content/samplecat.jpg" alt="category"/></a>
					    								</div>
					    							</div>
						    						<div class="col-xs-7 col-sm-7">
							    						<div class="less-title">
							    							<a href="">Beginning Literacy</a>
							    						</div>
							    						<p>Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Nullam quis risus eget urna mollis ornare vel eu leo.</p>
						    						</div>
					    						</div>
					    						
			    						</div>
			    					</li>
			    					<li class="less-listing course-thumbs cats">
			    						<a href=""></a>
			    						<div class="bg-arrow">
					    						<div class="row">
					    							<div class="col-xs-5 col-sm-5">
					    								<div class="cat-image">
					    									<a href=""><img src="/images/content/samplecat.jpg" alt="category"/></a>
					    								</div>
					    							</div>
						    						<div class="col-xs-7 col-sm-7">
							    						<div class="less-title">
							    							<a href="">Beginning Literacy</a>
							    						</div>
							    						<p>Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Nullam quis risus eget urna mollis ornare vel eu leo.</p>
						    						</div>
					    						</div>
					    						
			    						</div>
			    					</li>
			    					
			    					
			    				</ul>
			    			</div>
			    		</div>
			    		<div class="col-xs-12 col-sm-12">
			    			<p class="center nomargin"> <button type="submit" class="btn btn-default long-btn"><img class="home-search-icon" src="/images/arrows/more.png" /> Show more</button></p>
			    		</div>
			    		
			    		
			    	</div>
			    	
			    </div>
	    	</div>
	    </div>
