<div>
    <h3>Here is a list of all crops</h3>

</div>

<?php
$categories = $this->categories;
//echo print_r($categories);
while(next($categories))
{
    echo $categories[key($categories)]['crop_id']." ";
    echo $categories[key($categories)]['name_of_crop']." ";
    echo $categories[key($categories)]['altitude']." ";
    echo $categories[key($categories)]['farming_method']." ";
    echo $categories[key($categories)]['time_to_harvest']." ";
    echo "<br><br>";
}

?>

<!--<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12">
            <div class="jumbotrons">
                <img src="/images/content/samplecontent-img.jpg"/>
            </div>
            <div class="captionss">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12">
            <form class="form-inline nowrap" role="form" method="post" action="/search/search">
                <input type="text" class="form-control search-home" name="search_term" id="emailInput"> <button type="submit" class="btn btn-default search-home home-button">
                    <img class="home-search-icon" src="/images/arrows/search.png" />
                </button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12">
            <div class="span-full">
                <a href="/filter.php" class="btn btn-default"> Show filters</a>
            </div>
        </div>
    </div>
</div> <!-- /container -->

<!--<div class="container">
    <div class="lessons-wrap">
        <div class="class-thumbs-wrap">
            <div class="row">
                <div class="col-xs-12 col-sm-12">
                    <div class="coursthumbs">
                        <ul class="nopadding nomargin listnone listing-view">
                          
                            <p>sample content</p>

                        </ul>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12">
                    <p class="center nomargin"> <button type="submit" class="btn btn-default long-btn"><img class="home-search-icon" src="/images/arrows/more.png" /> Show more</button></p>
                </div>


            </div>

        </div>
    </div>
</div>
</div> <!-- /wrap -->
