<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12">
					<div class="jumbotrons">
						<img src="/images/content/samplecontent-img.jpg"/>
					</div>
					<div class="captionss">
					</div>
				</div>
				
				<div class="col-xs-12 col-sm-12">
					<form class="form-inline nowrap" role="form">
					    <input type="text" class="form-control search-home" id="emailInput"> <button type="submit" class="btn btn-default search-home home-button">
					    	<img class="home-search-icon" src="/images/arrows/search.png" />
					    </button>
					</form>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12">
					<div class="span-full">
						<a href="/filter.php" class="btn btn-default"><img class="home-search-icon" src="/images/arrows/filter.png" /> Show filters</a>
					</div>
				</div>
			</div>
	    </div> <!-- /container -->
	    
	    <div class="container">
	    	<div class="lessons-wrap">
	    		<div class="class-thumbs-wrap">
			    	<div class="row">
			    		<div class="col-xs-12 col-sm-12">
			    			<div class="coursthumbs">
			    				<ul class="nopadding nomargin listnone listing-view">
			    					<li class="less-listing course-thumbs">
			    						<div class="bg-arrow">
			    							<a href="/content.php">
					    						<div class="less-title">
					    							Week [ ]
					    						</div>
					    						<p>Nulla vitae elit libero, a pharetra augue. Nulla vitae elit libero, a pharetra augue. </p>
				    						 </a>
			    						</div>
			    					</li>
			    					<li class="less-listing course-thumbs">
			    						<div class="bg-arrow">
			    							<a href="/content.php">
					    						<div class="less-title">
					    							Week [ ]
					    						</div>
					    						<p>Nulla vitae elit libero, a pharetra augue. Nulla vitae elit libero, a pharetra augue. </p>
				    						 </a>
			    						</div>
			    					</li>
			    					<li class="less-listing course-thumbs">
			    						<div class="bg-arrow">
			    							<a href="/content.php">
					    						<div class="less-title">
					    							Week [ ]
					    						</div>
					    						<p>Nulla vitae elit libero, a pharetra augue. Nulla vitae elit libero, a pharetra augue. </p>
				    						 </a>
			    						</div>
			    					</li>
			    					<li class="less-listing course-thumbs">
			    						<div class="bg-arrow">
			    							<a href="/content.php">
					    						<div class="less-title">
					    							Week [ ]
					    						</div>
					    						<p>Nulla vitae elit libero, a pharetra augue. Nulla vitae elit libero, a pharetra augue. </p>
				    						 </a>
			    						</div>
			    					</li>
			    					<li class="less-listing course-thumbs">
			    						<div class="bg-arrow">
			    							<a href="/content.php">
					    						<div class="less-title">
					    							Week [ ]
					    						</div>
					    						<p>Nulla vitae elit libero, a pharetra augue. Nulla vitae elit libero, a pharetra augue. </p>
				    						 </a>
			    						</div>
			    					</li>
			    					<li class="less-listing course-thumbs">
			    						<div class="bg-arrow">
			    							<a href="/content.php">
					    						<div class="less-title">
					    							Week [ ]
					    						</div>
					    						<p>Nulla vitae elit libero, a pharetra augue. Nulla vitae elit libero, a pharetra augue. </p>
				    						 </a>
			    						</div>
			    					</li>
			    					<li class="less-listing course-thumbs">
			    						<div class="bg-arrow">
			    							<a href="/content.php">
					    						<div class="less-title">
					    							Week [ ]
					    						</div>
					    						<p>Nulla vitae elit libero, a pharetra augue. Nulla vitae elit libero, a pharetra augue. </p>
				    						 </a>
			    						</div>
			    					</li>
			    				</ul>
			    			</div>
			    		</div>
			    		<div class="col-xs-12 col-sm-12">
			    			<p class="center nomargin"> <button type="submit" class="btn btn-default long-btn"><img class="home-search-icon" src="/images/arrows/more.png" /> Show more</button></p>
			    		</div>
			    		
			    		
			    	</div>
			    	
			    </div>
	    	</div>
	    </div>
  </div> <!-- /wrap -->