<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" href="css/style.css" type="text/css">
        <script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
    </head>

    <body>

        <!-- Static navbar -->
        <div class="navbar-inverse myNav">
            <div class="navbar-inner">

                <div class="floatLeft navSpace">&nbsp</div>
                <a href="index.php"><div class="floatLeft hoverHand myOpacity" id="home" style=" margin-top: 1%;"><li class="icon-home" style="vertical-align: bottom"></li>&nbsp View</div></a>
                <div class="floatLeft navSpace">&nbsp</div>
                <a href="report.php"><div class=" floatLeft hoverHand myOpacity" id="reports" style="margin-top: 1%;"><li class="icon-align-justify" style="vertical-align: bottom"></li>&nbsp Enter Data</div></a>
                <div class="floatLeft navSpace">&nbsp</div>
            </div>
        </div>

            <?php echo $this->layout()->content; ?>

            <div id="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="copyright-wrap">
                                <p><b>Agric Test</b></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <!-- Bootstrap core JavaScript
            ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
            <script src="/js/bootstrap.min.js"></script>
    </body>
</html>
